### ISSUE TITLE
Web converter freeze

### ISSUE THREAD

**Issue by alex73** [a-student/SvgToVectorDrawableConverter.Web#1]
It doesn't convert anything - just freeze. I tried attached files

[icons.zip](https://github.com/a-student/SvgToVectorDrawableConverter.Web/files/143984/icons.zip)

**Comment by vlad-je** [comment]
![image](https://cloud.githubusercontent.com/assets/11069686/17045906/c5c5094e-4fef-11e6-8778-62e2707e6f25.png)

**Comment by a-student** [comment]
Thank you for the report.
Vladislav, please, use http://a-student.github.io/SvgToVectorDrawableConverter.Web/

**Comment by a-student** [comment]
Alex, it seems you've met the same issue. Thank you for reporting.
I made a redirect to http.
