### ISSUE TITLE
Any way to perform batch operations?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [a-student/SvgToVectorDrawableConverter.Web#2]
Is there a way to batch-convert multiple files?
Will it tell me of conversion issues?

**Comment by a-student** [comment]
You may try this tool https://github.com/a-student/SvgToVectorDrawableConverter
> Will it tell me of conversion issues?

Yes, when possible.

**Comment by AndroidDeveloperLB** [comment]
Nice, but can you please add option for batch operation on the online version?

**Comment by a-student** [comment]
Check out the new [site](http://a-student.github.io/SvgToVectorDrawableConverter.Web/). Up to 100 SVG files can be converted at a time

**Comment by AndroidDeveloperLB** [comment]
nice!
