### ISSUE TITLE
It doesn't do anything anymore

### ISSUE THREAD

**Issue by cristan** [a-student/SvgToVectorDrawableConverter.Web#3]
When I try to use it, after quite some time, I get the following error in my console (in Chrome):

OPTIONS http://193.124.64.166:5000/api/svg2vd/v2 net::ERR_CONNECTION_TIMED_OUT VM127:1

It also shows "Network Error" with a retry button, but this doesn't help

On Firefox, I get the Network Error screen only when I reload the screen, but I don't get an answer here too.

**Comment by a-student** [comment]
Please, make sure port 5000 is not blocked by your firewall / internet provider.
Does this happen every time with the same SVG image? Does it work well with the others?

Old version of the converter is available [here](http://a-student.github.io/SvgToVectorDrawableConverter.Web/old/). Does it work well?

**Comment by bvschaik** [comment]
Happens for all SVGs for me, the old version works fine.
Most corporate environments have only port 80 and 443 open... why host it on a non-standard port?

**Comment by cristan** [comment]
bvschaik was right: port 5000 was blocked at work. At home it worked just fine (with the same SVG).

**Comment by a-student** [comment]
The converter runs in browser now.
