### ISSUE TITLE
Can you do the conversion not only from the file but also from the svg code?

### ISSUE THREAD

**Issue by kepocnhh** [a-student/SvgToVectorDrawableConverter.Web#8]

**Comment by a-student** [comment]
Only from files. Could you please describe the case when you need conversion from code?

**Comment by kepocnhh** [comment]
For example, I as a developer get from the designer svg code. From a project with a design, I can export image files or immediately copy the code. In my case, I can do the conversion without exporting.

**Comment by a-student** [comment]
Try pasting SVG content - your feature request has been implemented.
